language: python
python:
    - "2.7"
cache:
    - pip
before_install:
    - export TZ=America/Denver
install: 
    - pip install codecov
    - pip install .
    - pip install -r requirements.txt
script: 
    - coverage run testAll.py
after_success:
     bash <(curl -s https://codecov.io/bash)
     codecov
    
    