language: python
python:
    - "2.7"
cache:
    - pip
install: 
    - pip install codecov
    - pip install .
    - pip install -r requirements.txt

script: 
    - python -m unittest testAll
after_success:
     bash <(curl -s https://codecov.io/bash)
    
    